name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -q --upgrade pip
        pip install -e .[linting]
        pip install -e .[tests]
        pip uninstall -y terragrunt-source
    - name: List installed dependencies
      run: |
        pip freeze
    - name: Build
      run: |
        make build
